---

# Airflow services management

- name: 'Create airflow tempfile directory'
  become: True
  template:
    src: "{{ role_path }}/templates/systemd/airflow.conf"
    dest: '/usr/lib/tmpfiles.d/airflow.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Manage webserver service with systemd'
  become: True
  template:
    src: "{{ role_path }}/templates/systemd/airflow-webserver.service"
    dest: '/lib/systemd/system/airflow-webserver.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart airflow-webserver'
  when: "{{ 'airflow-webserver' in airflow_managed_systemd_services }}"


- name: 'Manage webserver service with init.d'
  become: True
  template:
    src: "{{ role_path }}/templates/init.d/airflow-webserver.j2"
    dest: '/etc/init.d/airflow-webserver'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: 'Restart airflow-webserver'
  when: "{{ 'airflow-webserver' in airflow_managed_initd_services }}"


- name: 'Manage scheduler service with systemd'
  become: True
  template:
    src: "{{ role_path }}/templates/systemd/airflow-scheduler.service"
    dest: '/lib/systemd/system/airflow-scheduler.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart airflow-scheduler'
  when: "{{ 'airflow-scheduler' in airflow_managed_systemd_services }}"


- name: 'Manage scheduler service with init.d'
  become: True
  template:
    src: "{{ role_path }}/templates/init.d/airflow-scheduler.j2"
    dest: '/etc/init.d/airflow-scheduler'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: 'Restart airflow-scheduler'
  when: "{{ 'airflow-scheduler' in airflow_managed_initd_services }}"


- name: 'Manage worker service with systemd'
  become: True
  template:
    src: "{{ role_path }}/templates/systemd/airflow-worker.service"
    dest: '/lib/systemd/system/airflow-worker.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Restart airflow-worker'
  when: "{{ 'airflow-worker' in airflow_managed_systemd_services }}"


- name: 'Manage worker service with init.d'
  become: True
  template:
    src: "{{ role_path }}/templates/init.d/airflow-worker.j2"
    dest: '/etc/init.d/airflow-worker'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: 'Restart airflow-worker'
  when: "{{ 'airflow-worker' in airflow_managed_initd_services }}"


# Services states
- name: 'Manage airflow services states'
  become: True
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled | default(False) }}"
    state: "{{ item.state }}"
  with_items: "{{ airflow_services_states }}"
